version: '3'
services:
  yolo-app-db:
    image: mongo-express
    ports:
      - 27017:27017
    volumes: 
      - mongo_db:/data/db
    networks:
      - yolo
  yolo-app-frontend:
    build: client/
    image: client/yoloapp:1.0
    ports:
      - 3000:3000
    networks:
      - yolo
  yolo-app-backend:
    build: backend/
    image: backend/yoloapp:1.0
    ports:
      - 5001:5001
    networks:
      - yolo
    
networks:
  yolo:
    driver: bridge

volumes:
  mongo_db: {}